### ISSUE TITLE
Seats Reservation Edit 

### ISSUE THREAD

**Issue by kryschanhi** [ACTIONB34/JavaG1#18]
Related to #3 

**[Refer to the PHOTOS]**
Previously, customer reserved seats 5,8,7.
Assuming the customer wants to edit their reservation.
Customer has already reserved 5, but wants to input it again.
So it says "Oops! Seat Taken! Try again."

**_is this a BUG or NOT?_**
**_Should we do clear seat list before editing?_**

![bug1-1](https://user-images.githubusercontent.com/33647503/78468073-5377d600-7746-11ea-88ed-394d63909be8.PNG)
![bug1-2](https://user-images.githubusercontent.com/33647503/78468072-51157c00-7746-11ea-8ba4-47a19d8a8e84.PNG)
![bug1-3](https://user-images.githubusercontent.com/33647503/78468074-54a90300-7746-11ea-88b6-53482eec026d.PNG)

**Comment by chanelbaluyos** [comment]
gwapa ko

**Comment by isabellegly** [comment]
This happened sa akong testing haha!

**Comment by candacemadelo** [comment]
Okay nani :)

**Comment by kryschanhi** [comment]
**_Yay!_**
After pushing the new file, please close this issue. 
Thank you @candacemadelo !

**Comment by kryschanhi** [comment]
**Yay**
Thank you @candacemadelo !
