### ISSUE TITLE
Screen3B No Error Trapping for Customer Input

### ISSUE THREAD

**Issue by kryschanhi** [ACTIONB34/JavaG1#21]
Related to #3 

- [x] Negative Input Error Trapping
- [x] String Input Error Trapping
- [x] Zero all Input Error Trapping
- [x] Character Input Error Trapping

If wrong input such as
_**(characters or negative numbers or strings)**_

for 

"Enter # of Kids" 
"Enter # of Adults"
"Enter # of Seniors"

**_It doesn't show an error message._**

**Comment by kryschanhi** [comment]
@chanelbaluyos I added you because ikaw ang pro sa Screens. Thanks!

**Comment by kryschanhi** [comment]
![image](https://user-images.githubusercontent.com/33647503/78771151-48c97500-79c2-11ea-9108-e063cfa032ca.png)

_Would be better if there's an error already when the user inputs a number more than the capacity._

**Comment by kryschanhi** [comment]
![image](https://user-images.githubusercontent.com/33647503/78777104-87aff880-79cb-11ea-81a4-28aca3c75111.png)

Doesn't show error if the inputted number is beyond the available seats.

**Comment by chanelbaluyos** [comment]
fixed and verified
