### ISSUE TITLE
Seat Selection No Error Trapping for Negative Input or Zero

### ISSUE THREAD

**Issue by kryschanhi** [ACTIONB34/JavaG1#22]
Related to #3 

- [x] Negative Input Error Trapping
- [x] Zero Input Error Trapping
- [x] String Input Error Trapping
- [x] Character Input Error Trapping

![image](https://user-images.githubusercontent.com/33647503/78778129-59331d00-79cd-11ea-891e-8d29246a7a23.png)

**Comment by kryschanhi** [comment]
- [x] Error message for taken seat

![image](https://user-images.githubusercontent.com/33647503/78778664-36edcf00-79ce-11ea-8cd0-969a745339e2.png)

_**Related Error**_

No error message when it's zero and when the seat is already taken.

**Comment by chanelbaluyos** [comment]
fixed and verified
