### ISSUE TITLE
Error trappings

### ISSUE THREAD

**Issue by chanelbaluyos** [ACTIONB34/JavaG1#3]
Comment down below which part needs error trapping.
- [x] Please put a ✓  if it has already been implemented.

**Comment by chanelbaluyos** [comment]
- Error message if same seat ang ireserve

**Comment by chanelbaluyos** [comment]
- [ ] Error message if same seat ang ireserve

**Comment by isabellegly** [comment]
Nag try/catch man ta so I think ma handle ra most errors :)

**Comment by isabellegly** [comment]
**SCREEN3A**
- [x] Wrong Input in Cinema ID -> NullPointerException(unchecked) [must show invalid input error message]
- [x] Error Trapping for Number of Inputs: Include number of maximum input.

**Comment by chanelbaluyos** [comment]
- [ ] Add error trapping for Screen3B. Number of inputs of person type should not exist more than the available seats for that cinema. [must show invalid input error message]

**Comment by chanelbaluyos** [comment]
**SCREEN3C**
- [x] Error message if same seat ang ireserve
- [x] Same number of seat is chosen
![image](https://user-images.githubusercontent.com/30874903/78459847-a4f47680-76ee-11ea-8edb-3066be73696d.png)

- [x] Invalid inputs should not be printed out. Number of People should be equal to number of seats.
![image](https://user-images.githubusercontent.com/30874903/78459872-ca818000-76ee-11ea-9a88-6c391d1610aa.png)

**Comment by candacemadelo** [comment]
Okay nani :)
